openapi: 3.0.3

info:
  title: E-commerce API
  version: 1.0.0
  description: Documentation of API for the E-commerce project.

servers:
  - url: http://localhost:5000

tags:
  - name: Products
    description: Daftar dan detail produk untuk katalog toko.
  - name: Carts
    description: Operasi keranjang belanja untuk user yang login.
  - name: Auth
    description: Autentikasi (register, login) dan token JWT.

security:
  - bearerAuth: []

paths:

  /auth/me:
    $ref: ./paths/auth/me.yaml

  /auth/login:
    $ref: ./paths/auth/login.yaml

  /auth/register:
    $ref: ./paths/auth/register.yaml

  /products:
    $ref: ./paths/products/list-products.yaml

  /products/{productId}:
    $ref: ./paths/products/product-detail.yaml

  /carts/me:
    $ref: ./paths/carts/get-cart.yaml

  /carts/me/items:
    $ref: ./paths/carts/add-cart-item.yaml

  /carts/me/items/{cartItemId}:
    $ref: ./paths/carts/update-cart-item.yaml





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Token JWT (Authorization: Bearer <token>)"

  schemas:

    User:
      $ref: ./schemas/User.yaml#/User

    UserCreateRequest:
      $ref: ./schemas/User.yaml#/UserCreateRequest

    Product:
      $ref: ./schemas/Product.yaml#/Product

    LoginResponse:
      $ref: ./schemas/Auth.yaml#/LoginResponse


    AuthSuccessData:
      $ref: ./schemas/Auth.yaml#/AuthSuccessData

    LoginRequest:
      $ref: ./schemas/Auth.yaml#/LoginRequest
  
    ErrorResponse:
      $ref: ./schemas/ErrorResponse.yaml#/ErrorResponse

    CartItem:
      $ref: ./schemas/CartItem.yaml#/CartItem

    CartItemCreateRequest:
      $ref: ./schemas/CartItem.yaml#/CartItemCreateRequest

    Cart: 
      $ref: ./schemas/Cart.yaml#/Cart

    